version: '3.8'
services:
  bot:
    build: .
    container_name: pa_bot
    restart: always

    environment:
     BOT_TOKEN: ${PA_TOKEN}
     API_ID: ${API_ID}
     API_HASH: ${API_HASH}
    network_mode: host
    
    volumes:
     - type: volume
       source: bot_data
       target: /app

volumes:
 bot_data:         


